---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: decentnoobbot-secret
  namespace: decentnoobbot
spec:
  encryptedData:
    bot-token: AgCTHAC3RLsaMXQo7/E1HPS1KF91PeZonoJAluHoAOcDimLZKSncsmDpSQkZ+WEWX3rV+0WDw/ZlC3CIasfDYqG0ijdOZHOYBkSzcyxXECScQi+xF1R2GrmlSyPKAWp8KlUnm95OTvshc7DoDzV4c4PFdGippkL2Ac1yNik68NMhUfBWhe2tquFNCVLT6jPeM+LjY+570MiDzXbAFQycxBrGS2oI7su04yRINCZHG2vn8v6UDVa9GsZNwrXSjxGSGfMF6c2rYa78x6hgMoi99Td3NoL7Ta8AnSPWDDLxE2fjYHlCSVHqj9ueYSLtLR7rCcYn4LB5CV4kf+YMkJQlHCvj3X7MTZ622w+QD81UUj8LrZKD9XcOJFfJICnQh5D2Oo6pkEgq8seDAjkBMPkOpysC+ervOHCj4HPpzyIEXbw18Bzr0EM4h1QGqHRs8xvsNibBWzS4ITzUBzoDbuFrJ3OlmFLJB4yWSfl9qfX+QiJFobR8fDtETGJeSXOC+KCAH6ICajZ1ItOsd4DQHWM5oV5T7n5WIfEM/dOFaHQrEBSFyQajgslCvC18wRcaAk0s4YFAuDPLz9y1D2LtLJ/Ka2DAc8eSHgrKpgmoTwUzx5OwFXN4JxmcRaMAo4tYhk+CNaY2pyE4YeQcmvi1OAZZpHFhC9vmKD+5O72eBUFnWLPq6ScnsT4Dcs6+szKm2Mgg2Qk4DBGKUoUsIerkwqA/qCSLpZOGV+zVGzjjtT5lNysjO8ZDomtUIrIXer80uaNpAFps/5TxP3cExFRreai6/N+xno051IQ1
  template:
    metadata:
      name: decentnoobbot-secret
      namespace: decentnoobbot
    type: Opaque
