---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: decentnoobbot-secret
  namespace: decentnoobbot
spec:
  encryptedData:
    bot-token: AgAwha9DmsMwOBs9mlh3WaecN5eFPk4vnVNQDgT0COzDdFfjT0PkbHI+m6x6JCNIxhaaY3qa0a+XsG4ultCxGwIcr/ooJcmyyH/6xRhT7/CGC7snDPk76ucpVCpTk46D5IafAOH7Xhz+CC5+JagwmhRWmTklGqacm/hWlxHqDvsi0dWeXHMebunlLR53xWr0BGr1jJwCZsQDwyZOx7VKTE6wKhLbM0q0wgH3p4VKoItekeKfs8z0YayjHEThT31Yt8zSsXSktQ1mEfcTlgwmx49/QpIhhCRDEhHr4FM2d3kJLYX8eGzjW6D2mr+Ls18dbb7poBPqm5AK9tLwGCkQfiWnZZvdAYMw6hEw+FfmjOFUaOsrLd/qujkxTMSPNDL70cgo+eZvLeT/Ap51Ip2+xmwBJtTN4rl+q01OO/wv+aiOBHe5hklSCuCDDpPnXO3V0V/XDizOJGECjBOo+QIF5M6OXgeJShtiHvrwgCEStfo2LT0D6FGYSEzuG1+gjkRXb4hlG4s5Nw6d7GX2H4F+uiwqc3za5Lj+KWf6EX2rGH6LAMuJ8Mzpczu6E3ZPpQ6tqNwge8/hw/BKD8ju5JmrMHP3VjpgNIf1ZhNxJlyq0w36yfJujwgnuFGVXZToedhw78OBEZoqwEhY40MFtZ8uv/ZgK1GOUO5vaTRMJ0H+gBYZ/vgWyQQFyxbBPje81Z9fyGC6OU0Jk26ersWMchPmcV/DRgMSyyy7PAl40eg5WMZhkD7a6x5ntwM44GQwUMtvRUCFtvazI2SSctynWorbHQvROxwfOQyLZw==
  template:
    metadata:
      name: decentnoobbot-secret
      namespace: decentnoobbot
    type: Opaque
